In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pickle
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
scaler = StandardScaler()

In [ ]:
with open('/content/drive/MyDrive/Colab Notebooks/ML-Ops/P2/scaler.pkl','rb') as f:
  scaler = pickle.load(f)

In [ ]:
X_test = np.load('/content/drive/MyDrive/Colab Notebooks/ML-Ops/P2/X_test.npy', allow_pickle=True)
X_train = np.load('/content/drive/MyDrive/Colab Notebooks/ML-Ops/P2/X_train.npy', allow_pickle=True)

In [ ]:
X_test = np.asarray(X_test).reshape(-1,1)
X_train = np.asarray(X_train).reshape(-1,1)

In [ ]:
X_test_Normalized = scaler.transform(X_test)
X_train_Normalized = scaler.transform(X_train)

In [ ]:
X_test_Normalized

array([[ 3.5846748 ],
       [-0.74521085],
       [-0.7728999 ],
       [-0.46621978],
       [-0.80481733],
       [ 0.44468181],
       [ 2.95178219],
       [ 0.97372001],
       [-0.66233465],
       [-0.55337892],
       [-0.42262658],
       [-0.43394772],
       [-0.63759182],
       [ 1.27925437],
       [-0.08563855],
       [-0.62166039],
       [-0.72251401],
       [-0.65597845],
       [-0.84000834],
       [-0.24899031]])

In [ ]:
X_train_Normalized

array([[-0.70846488],
       [ 0.54488071],
       [-0.71997698],
       [-0.75271281],
       [-0.48700703],
       [-0.61293084],
       [-0.84131777],
       [-0.65728788],
       [ 1.64371321],
       [-0.25109086],
       [ 1.43365834],
       [-0.78735822],
       [ 1.37418826],
       [-0.58286844],
       [ 0.0666376 ],
       [-0.28521795],
       [ 3.32878977],
       [-0.05598535],
       [-0.48373345],
       [-0.58172268],
       [ 0.01977081],
       [ 0.11988787],
       [-0.48550664],
       [ 0.76884831],
       [-0.29130136],
       [-0.82683217],
       [ 2.94796301],
       [-0.1460907 ],
       [ 0.07359396],
       [-0.70210868],
       [-0.30974254],
       [-0.82072148],
       [ 1.28143676],
       [-0.45077939],
       [-0.16368621],
       [-0.18065428],
       [ 0.58252691],
       [-0.01165558],
       [ 0.10327444],
       [-0.50861268],
       [-0.73702689],
       [-0.49262668],
       [-0.64514834],
       [-0.16324973],
       [ 0.04268589],
       [-0

In [ ]:
X_test

array([[21.279 ],
       [ 5.4069],
       [ 5.3054],
       [ 6.4296],
       [ 5.1884],
       [ 9.7687],
       [18.959 ],
       [11.708 ],
       [ 5.7107],
       [ 6.1101],
       [ 6.5894],
       [ 6.5479],
       [ 5.8014],
       [12.828 ],
       [ 7.8247],
       [ 5.8598],
       [ 5.4901],
       [ 5.734 ],
       [ 5.0594],
       [ 7.2259]])

In [ ]:
X_train

array([[ 5.5416],
       [10.136 ],
       [ 5.4994],
       [ 5.3794],
       [ 6.3534],
       [ 5.8918],
       [ 5.0546],
       [ 5.7292],
       [14.164 ],
       [ 7.2182],
       [13.394 ],
       [ 5.2524],
       [13.176 ],
       [ 6.002 ],
       [ 8.3829],
       [ 7.0931],
       [20.341 ],
       [ 7.9334],
       [ 6.3654],
       [ 6.0062],
       [ 8.2111],
       [ 8.5781],
       [ 6.3589],
       [10.957 ],
       [ 7.0708],
       [ 5.1077],
       [18.945 ],
       [ 7.6031],
       [ 8.4084],
       [ 5.5649],
       [ 7.0032],
       [ 5.1301],
       [12.836 ],
       [ 6.4862],
       [ 7.5386],
       [ 7.4764],
       [10.274 ],
       [ 8.0959],
       [ 8.5172],
       [ 6.2742],
       [ 5.4369],
       [ 6.3328],
       [ 5.7737],
       [ 7.5402],
       [ 8.2951],
       [ 5.0702],
       [10.236 ],
       [ 5.1793],
       [ 8.2934],
       [ 5.0365],
       [ 6.8825],
       [ 9.3102],
       [11.7   ],
       [ 6.5159],
       [ 5.6397],
       [ 9